stateDiagram-v2
    state "Start" as Start
    state "Transition" as Transition
    state "End" as End

    [*] --> Start: myList = [1,2,3] and x = 5 and test = [0,1]
    Start --> Transition: x = 1
    Transition --> End: x = 2
