"""
cbmc_builder.py — Top-level builder for CBMC C file generation.

Mirrors PromelaBuilder: three with_*() setters, one build() → Result[str, Error].

The generated C file has this structure:
  1. File header
  2. #include <stdbool.h>, nondet_int() declaration
  3. State #defines (consts, enum values)
  4. BOUND #define
  5. CWP state #defines  (from CwpCbmcVisitor)
  6. Transition #defines (from BpmnCbmcVisitor)
  7. update_cwp_state()  (from CwpCbmcVisitor)
  8. int main()          (from BpmnCbmcVisitor)
"""

from returns.result import Failure, Result, Success

from bpmncwpverify.builder.cbmc_bound import compute_bound
from bpmncwpverify.core.bpmn import Bpmn
from bpmncwpverify.core.cwp import Cwp
from bpmncwpverify.core.error import CbmcGeneratorError, Error, NotInitializedError
from bpmncwpverify.core.state import State
from bpmncwpverify.visitors.bpmn_cbmc_visitor import BpmnCbmcVisitor
from bpmncwpverify.visitors.cwp_cbmc_visitor import CwpCbmcVisitor

# ── State-to-C helpers ────────────────────────────────────────────────────────


def _state_defines(state: State) -> str:
    """
    Emit C #define lines for consts and enum values.

    Consts:     #define <id>  <init_value>
    Enum vals:  #define <value>  N   (sequential per enum, 0-based)
    """
    lines: list[str] = []
    for const in state.consts:
        lines.append(f"#define {const.id:<28} {const.init.value}")
    for enum in state.enums:
        for i, val in enumerate(enum.values):
            lines.append(f"#define {val.value:<28} {i}")
    return "\n".join(lines) + "\n" if lines else ""


def _var_decls(state: State) -> list[str]:
    """
    C variable declarations for main() — bare-bones: all as int.
    e.g. ["int x = 0;"] or ["int terms = TERMS_PENDING;"]
    """
    decls: list[str] = []
    enum_ids = {e.id for e in state.enums}
    for var in state.vars:
        # bare bones: always declare as int regardless of type_
        _ = enum_ids  # noted: ignored in this bare-bones version
        decls.append(f"int {var.id} = {var.init.value};")
    return decls


def _var_params(state: State) -> list[str]:
    """
    C parameter declarations for update_cwp_state() — bare-bones: all int.
    e.g. ["int x"] or ["int terms", "int paymentOffered", ...]
    """
    return [f"int {var.id}" for var in state.vars]


def _var_args(state: State) -> list[str]:
    """
    Call arguments for update_cwp_state() — just variable names.
    e.g. ["x"] or ["terms", "paymentOffered", ...]
    """
    return [var.id for var in state.vars]


# ── C file assembly ────────────────────────────────────────────────────────────


def _generate_c(
    state: State, cwp: Cwp, bpmn: Bpmn, max_retries: int
) -> Result[str, Error]:
    # ── Run CWP visitor ──
    cwp_visitor = CwpCbmcVisitor()
    cwp.accept(cwp_visitor)

    # ── Run BPMN visitor ──
    bpmn_visitor = BpmnCbmcVisitor()
    bpmn.accept(bpmn_visitor)

    if bpmn_visitor.error is not None:
        return Failure(bpmn_visitor.error)

    if bpmn_visitor.num_transitions == 0:
        return Failure(CbmcGeneratorError("BPMN produced no transitions"))

    # ── Derived values ──
    bound = compute_bound(bpmn, max_retries)
    st_defines = _state_defines(state)
    v_decls = _var_decls(state)
    v_params = _var_params(state)
    v_args = _var_args(state)

    initial_cwp = cwp_visitor.initial_cwp_state_define()
    cwp_reached_init = cwp_visitor.cwp_reached_init_expr()
    cwp_define_names = cwp_visitor.reachable_state_define_names()

    # ── Assemble ──
    sections: list[str] = []

    sections.append(
        "/* Auto-generated by cbmc_builder.py — do not edit by hand. */\n"
        "#include <stdbool.h>\n"
        "\n"
        "int nondet_int();\n"
    )

    if st_defines:
        sections.append(st_defines)

    sections.append(f"#define {'BOUND':<28} {bound}\n")

    sections.append(cwp_visitor.generate_state_defines())

    sections.append(bpmn_visitor.generate_transition_defines())

    sections.append(cwp_visitor.generate_update_cwp_state(v_params))

    sections.append(
        bpmn_visitor.generate_main(
            var_decls=v_decls,
            var_args=v_args,
            initial_cwp_state=initial_cwp,
            cwp_num_states_define="CWP_NUM_STATES",
            cwp_reached_init=cwp_reached_init,
            cwp_state_define_names=cwp_define_names,
        )
    )

    return Success("\n".join(sections))


# ── Builder class ──────────────────────────────────────────────────────────────


class CbmcBuilder:
    __slots__ = ["bpmn", "cwp", "state", "max_retries"]

    def __init__(self) -> None:
        self.bpmn: Result[Bpmn, Error] = Failure(
            NotInitializedError("CbmcBuilder.bpmn")
        )
        self.cwp: Result[Cwp, Error] = Failure(NotInitializedError("CbmcBuilder.cwp"))
        self.state: Result[State, Error] = Failure(
            NotInitializedError("CbmcBuilder.state")
        )
        self.max_retries: int = 2

    def with_bpmn(self, bpmn: Bpmn) -> "CbmcBuilder":
        self.bpmn = Success(bpmn)
        return self

    def with_cwp(self, cwp: Cwp) -> "CbmcBuilder":
        self.cwp = Success(cwp)
        return self

    def with_state(self, state: State) -> "CbmcBuilder":
        self.state = Success(state)
        return self

    def with_max_retries(self, max_retries: int) -> "CbmcBuilder":
        self.max_retries = max_retries
        return self

    def build(self) -> Result[str, Error]:
        max_retries = self.max_retries
        result: Result[str, Error] = self.state.bind(  # pyright: ignore[reportUnknownMemberType]
            lambda state: self.cwp.bind(  # pyright: ignore[reportUnknownMemberType]
                lambda cwp: self.bpmn.bind(  # pyright: ignore[reportUnknownMemberType]
                    lambda bpmn: _generate_c(state, cwp, bpmn, max_retries)
                )
            )
        )
        return result
